services:
  postgres:
    image: postgres:15-alpine
    container_name: pobris-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pobris_db
      POSTGRES_USER: pobris_user
      POSTGRES_PASSWORD: pobris_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - pobris-network

  # Opcional: pgAdmin para gerenciar o banco via interface web
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pobris-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pobris.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pobris-network

volumes:
  postgres_data:

networks:
  pobris-network:
    driver: bridge
